# Generated by Django 5.1.3 on 2024-11-19 20:28

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(upload_to='invoices/', validators=[invoices.models.validate_file_extension]),
        ),
    ]
